apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agrisense-staging

resources:
  - ../base/gateway
  - ../base/brain
  - ../base/farm
  - ../base/agronomy
  - ../base/finance
  - ../base/marketplace
  - ../base/analytics
  - ../base/ai
  - ../base/platform

patches:
  - path: replica-patch.yaml

images:
  - name: gcr.io/REPLACE_PROJECT_ID/agrisense
    newTag: staging

commonLabels:
  environment: staging
